#!/usr/bin/perl

use strict;
use warnings;

use lib './lib';

use Silk::Config;

system( 'psql', 'template1', '-f', './schema/Silk.sql' )
    and die 'Cannot create Silk database with psql';


require Silk::Model::Domain;

Silk::Model::Domain->EnsureRequiredDomainsExist();

require Silk::Model::User;

Silk::Model::User->EnsureRequiredUsersExist();

print "\n";

my $admin = make_admin_user();
make_first_wiki($admin);

sub make_admin_user
{
    my $email = 'admin@' . Silk::Model::Domain->DefaultDomain()->hostname();
    my $pw = 'changeme';

    my $admin =
        Silk::Model::User->insert( display_name       => 'Angela D. Min',
                                   email_address      => $email,
                                   password           => $pw,
                                   is_admin           => 1,
                                   created_by_user_id => Silk::Model::User->SystemUser()->user_id(),
                                 );

    print <<"EOF";
Created the admin user:

  email:    $email
  password: $pw

EOF
}

sub make_first_wiki
{
    require Silk::Model::Wiki;

    my $wiki =
        Silk::Model::Wiki->insert( title      => 'The First Wiki',
                                   short_name => 'first-wiki',
                                   domain_id  => Silk::Model::Domain->DefaultDomain()->domain_id(),
                                   user_id    => Silk::Model::User->SystemUser()->user_id(),
                                 );

#    require Silk::Model::Page;

#    my $page = Silk::Model::Page->

    my $uri = $wiki->base_uri();

    print <<"EOF";
Created the first wiki:

  URI: $uri

EOF

}

